# SPDX-License-Identifier: GPL-3.0-only
# Prevent interactive "which registry?" prompt in non-TTY contexts.
# Without this, `podman pull postgres` blocks waiting for user input
# when multiple registries match. Permissive mode auto-selects the
# first match from unqualified-search-registries.

[registries.search]
registries = ["docker.io"]

[registries]
short-name-mode = "permissive"
unqualified-search-registries = ["docker.io"]
